application: rss-proxy
version: 1
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: media

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: common/appenginepatch/main.py
