application: rss-proxy
version: 1
runtime: python
api_version: 1

default_expiration: "1h"

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /(robots\.txt|favicon\.ico|feeds/feedfetcher-without-subscribers\.xml|feeds/livejournal-403-bots\.xml)
  static_files: static/\1
  upload: static/(robots\.txt|favicon\.ico|feeds/feedfetcher-without-subscribers\.xml|feeds/livejournal-403-bots\.xml)

- url: /.*
  script: common/appenginepatch/main.py
